version: '3.7'

services:
  db:
    container_name: 'coffee_db'
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - coffee-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DATABASE_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DATABASE_NAME}"
  api:
    container_name: 'coffee_api'
    build:
      context: '.'
    ports:
      - "${SERVER_PUBLIC_PORT}:${SERVER_PORT}"
    volumes:
      - .env:/home/node/app/.env

volumes:
  coffee-data:
